"""Receipts v2: verify-only Ed25519/BLAKE3 signature envelope.

Acceptance coverage maps 1:1 to docs/RECEIPTS-V2.md's sketch:
  test_acceptance_*     — the design note's four acceptance tests
  test_primitives_*     — known-answer pins for the vendored crypto
  test_key_rotation_*   — retirement receipts (design note rule)
  test_refusal_*        — refusal polarity booked to the WAL, not silent
  test_real_sibling_*   — family cross-repo contract, REAL twist-engine
                          rows as fixtures (generated by running the
                          sibling's shipped code — see fixture provenance)
  test_cross_language_* — vectors/signed_receipt_vectors.json byte pins
"""

import json
import os
import unittest

from jev_quilt.bookkeeper import Bookkeeper, Receipt, fnv1a
from jev_quilt import ed25519
from jev_quilt.blake3 import blake3
from jev_quilt import signed_receipts as sr

FIXTURE = os.path.join(os.path.dirname(__file__),
                       "fixtures", "twist_engine_sibling_rows.json")
VECTORS = os.path.join(os.path.dirname(__file__), os.pardir,
                       "vectors", "signed_receipt_vectors.json")


def _book_demo(n=3):
    bk = Bookkeeper("v2.demo")
    for i in range(n):
        bk.book({"phase": i}, {"delta": i + 1}, "decided", {"row": i})
    return bk


def _fixed_id(seed_byte: int = 0):
    # Deterministic TEST identity (never a real node key — same standing
    # as the vectors file's all-zero seed). Cross-node tests pass
    # DIFFERENT seed bytes per node, or the negative case is vacuous.
    seed = bytes([seed_byte]) * 32
    return f"testnode{seed_byte}.k1", seed.hex(), ed25519.publickey(seed).hex()


class TestPrimitives(unittest.TestCase):
    def test_blake3_known_answers(self):
        self.assertEqual(
            blake3(b"").hex(),
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262")
        self.assertEqual(
            blake3(b"abc").hex(),
            "6437b3ac38465133ffb63b75273a8db548c558465d79db03fd359c6cd5bd9d85")

    def test_blake3_refuses_beyond_one_chunk(self):
        with self.assertRaises(ValueError):
            blake3(b"x" * 1025)

    def test_ed25519_known_answer_vector(self):
        v = json.load(open(VECTORS))["ed25519"]
        seed = bytes.fromhex(v["seed_hex"])
        self.assertEqual(ed25519.publickey(seed).hex(), v["public_key_hex"])
        sig = ed25519.sign(seed, bytes.fromhex(v["message_hex"]))
        self.assertEqual(sig.hex(), v["signature_hex"])
        self.assertTrue(ed25519.verify(
            bytes.fromhex(v["public_key_hex"]),
            bytes.fromhex(v["message_hex"]), sig))

    def test_ed25519_tamper_and_wrong_key_refused(self):
        seed_a, seed_b = os.urandom(32), os.urandom(32)
        pk_a = ed25519.publickey(seed_a)
        sig = ed25519.sign(seed_a, b"ledger row")
        self.assertFalse(ed25519.verify(pk_a, b"ledger row!", sig))
        self.assertFalse(ed25519.verify(ed25519.publickey(seed_b),
                                       b"ledger row", sig))
        self.assertFalse(ed25519.verify(pk_a, b"ledger row", sig[:63]))


class TestEnvelopeHappyPath(unittest.TestCase):
    def test_sign_and_verify(self):
        bk = _book_demo()
        signer, seed_hex, pk_hex = _fixed_id()
        signed = [sr.seal(r, bk.replay(), signer, seed_hex) for r in bk.entries]
        pubkeys = {signer: pk_hex}
        for s in signed:
            v = sr.verify_envelope(s, pubkeys, expected_chain_tip=bk.replay())
            self.assertTrue(v["ok"], v)
            self.assertEqual(v["reasons"], [])

    def test_deterministic_signatures(self):
        bk = _book_demo()
        signer, seed_hex, _ = _fixed_id()
        a = sr.seal(bk.entries[0], bk.replay(), signer, seed_hex)
        b = sr.seal(bk.entries[0], bk.replay(), signer, seed_hex)
        self.assertEqual(a.signature, b.signature)  # Ed25519 is deterministic


class TestAcceptanceSketch(unittest.TestCase):
    def test_acceptance_tamper_chain_and_signature_fail_independently(self):
        # Acceptance 2: flip one payload bit → chain re-derivation fails
        # AND signature verification fails, independently.
        bk = _book_demo()
        signer, seed_hex, pk_hex = _fixed_id()
        signed = sr.seal(bk.entries[1], bk.replay(), signer, seed_hex)

        forged = Receipt(**{**signed.receipt.__dict__,
                            "payload": signed.receipt.payload.replace(
                                '"row": 1', '"row": 9')})
        # (a) the chain's own rule: sha() re-derives payload_hash from the
        # residue, so the forged receipt hashes differently than booked
        booked_hash = signed.receipt.sha()
        self.assertNotEqual(forged.sha(), booked_hash)
        # (b) the envelope fails on the forged material
        v = sr.verify_envelope(
            sr.SignedReceipt(receipt=forged, chain_head=signed.chain_head,
                             signer=signer, signature=signed.signature),
            {signer: pk_hex}, expected_chain_tip=bk.replay())
        self.assertFalse(v["ok"])
        self.assertEqual(v["reasons"], ["bad_signature"])
        # (c) independence: the envelope verdict does not depend on the
        # chain having been checked first — a fresh verifier with only
        # pubkeys catches it too
        v2 = sr.verify_envelope(
            sr.SignedReceipt(receipt=forged, chain_head=signed.chain_head,
                             signer=signer, signature=signed.signature),
            {signer: pk_hex})
        self.assertEqual(v2["reasons"], ["bad_signature"])

    def test_acceptance_strip_backward_compat(self):
        # Acceptance 3: a verifier that ignores envelopes reproduces
        # today's behavior bit-for-bit.
        bk = _book_demo()
        before = bk.replay()
        signer, seed_hex, _ = _fixed_id()
        envelopes = [sr.seal(r, before, signer, seed_hex) for r in bk.entries]
        # strip: the receipt objects inside the envelopes ARE the v1 rows
        stripped = [e.receipt for e in envelopes]
        self.assertEqual(stripped, bk.entries)
        self.assertEqual(bk.replay(), before)
        # and the v1 structural verifier still passes untouched
        self.assertTrue(bk.verify())

    def test_acceptance_cross_node_negative(self):
        # Acceptance 4: node A signs, node B verifies, node B CANNOT mint
        # an A receipt with its own key.
        bk = _book_demo(1)
        _, seed_a, pk_a = _fixed_id(seed_byte=0)
        _, seed_b, pk_b = _fixed_id(seed_byte=1)
        self.assertNotEqual(pk_a, pk_b)  # the negative case needs two keys
        pubkeys = {"nodeA.k1": pk_a}
        genuine = sr.seal(bk.entries[0], bk.replay(), "nodeA.k1", seed_a)
        self.assertTrue(sr.verify_envelope(genuine, pubkeys)["ok"])

        # B forges an envelope claiming to be A
        ch, sig_b = sr.seal_bytes(sr.canonical_bytes(bk.entries[0]),
                                  bk.replay(), "nodeB.k1", seed_b)
        forged = sr.SignedReceipt(receipt=bk.entries[0], chain_head=ch,
                                  signer="nodeA.k1", signature=sig_b)
        v = sr.verify_envelope(forged, pubkeys)
        self.assertFalse(v["ok"])
        self.assertEqual(v["reasons"], ["bad_signature"])

        # B's honest envelope under its own id verifies fine
        honest = sr.SignedReceipt(receipt=bk.entries[0], chain_head=ch,
                                  signer="nodeB.k1", signature=sig_b)
        self.assertTrue(sr.verify_envelope(
            honest, {"nodeB.k1": pk_b})["ok"])

    def test_unknown_signer_is_refusal_not_exception(self):
        bk = _book_demo(1)
        _, seed_hex, pk_hex = _fixed_id()
        signed = sr.seal(bk.entries[0], bk.replay(), "ghost.k9", seed_hex)
        v = sr.verify_envelope(signed, {"someone.else": pk_hex})
        self.assertFalse(v["ok"])
        self.assertEqual(v["reasons"], ["unknown_signer"])

    def test_wrong_chain_head_refused(self):
        bk = _book_demo(1)
        signer, seed_hex, pk_hex = _fixed_id()
        signed = sr.seal(bk.entries[0], bk.replay(), signer, seed_hex)
        v = sr.verify_envelope(signed, {signer: pk_hex},
                               expected_chain_tip="f" * 64)
        self.assertFalse(v["ok"])
        self.assertEqual(v["reasons"], ["wrong_chain_head"])


class TestKeyRotation(unittest.TestCase):
    def test_retirement_signed_by_new_key(self):
        old_seed = bytes([0]) * 32
        new_seed = bytes([1]) * 32
        old_id, new_id = "node.k1", "node.k2"
        old_pk = ed25519.publickey(old_seed).hex()
        new_pk = ed25519.publickey(new_seed).hex()
        payload = sr.rotation_payload(old_id, old_pk, new_id, new_pk,
                                      note="scheduled rotation")
        sig = sr.sign_rotation(payload, new_id, new_seed.hex())
        self.assertTrue(sr.verify_rotation(payload, new_pk, sig))
        # tamper the old key out of the payload → refusal
        evil = sr.rotation_payload(old_id, old_pk.replace("00", "11", 1),
                                   new_id, new_pk)
        self.assertFalse(sr.verify_rotation(evil, new_pk, sig))


class TestRefusalPolarity(unittest.TestCase):
    def test_failed_verification_booked_to_wal(self):
        # Family doctrine: refusal polarity is a first-class ledger row.
        # A bad envelope is BOOKED as v2-refused, never swallowed.
        bk = _book_demo(1)
        signer, seed_hex, pk_hex = _fixed_id()
        signed = sr.seal(bk.entries[0], bk.replay(), signer, seed_hex)
        forged = sr.SignedReceipt(
            receipt=Receipt(**{**signed.receipt.__dict__,
                               "decision_kind": "fabricated"}),
            chain_head=signed.chain_head, signer=signer,
            signature=signed.signature)
        verdict = sr.verify_envelope(forged, {signer: pk_hex})
        self.assertFalse(verdict["ok"])

        booked = bk.book({"envelope_check": "cross-node"},
                         {"target": "tip"}, "v2-refused",
                         {"signer": verdict["signer"],
                          "reasons": verdict["reasons"]})
        self.assertEqual(booked.decision_kind, "v2-refused")
        self.assertIn("bad_signature", booked.payload)
        # the refusal row is IN the chain: replay covers it, verify() passes
        self.assertTrue(bk.verify())
        self.assertEqual(bk.replay(), bk.replay())  # stable
        self.assertEqual(len(bk.entries), 2)

    def test_secret_never_in_serialized_form(self):
        _, seed_hex, _ = _fixed_id()
        bk = _book_demo(1)
        signed = sr.seal(bk.entries[0], bk.replay(), "n.k1", seed_hex)
        blob = signed.to_canonical_json()
        self.assertNotIn(seed_hex, blob)
        self.assertNotIn("seed", blob)
        # repr paths too
        self.assertNotIn(seed_hex, repr(signed))


class TestRealSiblingRows(unittest.TestCase):
    """Family cross-repo contract, exercised with REAL sibling rows:
    the fixture was produced by running twist-engine's shipped
    jev-receipts.mjs (see the fixture's provenance block)."""

    def setUp(self):
        fx = json.load(open(FIXTURE))
        self.fx = fx
        self.entries = fx["entries"]

    def _twist_chain_reverify(self):
        # Re-verify the sibling's chain in-test, porting jev-receipts.mjs
        # exactly (twist-engine @23047cb): hv accumulates across BOTH
        # rounds (no reset between rounds — the subtle part), iterated
        # over code points, h becomes "0x"+16hex of the running hv.
        # Self-contained — no node needed in CI.
        def twist_hash(parent, body):
            hv = 0xcbf29ce484222325
            h = parent + body
            for _ in range(2):
                for ch in h:  # Python iterates code points == JS for-of
                    hv ^= ord(ch)
                    hv = (hv * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
                h = "0x" + format(hv, "016x")
            return h

        prev = "0" * 64
        for e in self.entries:
            self.assertEqual(e["parent"], prev)
            self.assertEqual(twist_hash(e["parent"], e["body"]), e["hash"])
            prev = e["hash"]
        return prev

    def test_fixture_chain_is_intact(self):
        tip = self._twist_chain_reverify()
        self.assertEqual(tip, self.fx["chain_tip"])

    def test_seal_and_verify_real_sibling_row(self):
        self._twist_chain_reverify()
        signer, seed_hex, pk_hex = _fixed_id()
        alarm = self.entries[4]  # the jev.alarm row — a real alarm booking
        # canonical form for a foreign receipt: its own substrate's rule
        canonical = (alarm["body"] + alarm["hash"]).encode("utf-8")
        ch, sig = sr.seal_bytes(canonical, self.fx["chain_tip"], signer,
                                seed_hex)
        v = sr.verify_bytes(canonical, ch, signer, sig, {signer: pk_hex},
                            expected_chain_tip=self.fx["chain_tip"])
        self.assertTrue(v["ok"], v)

    def test_sibling_tamper_caught(self):
        self._twist_chain_reverify()
        signer, seed_hex, pk_hex = _fixed_id()
        row = self.entries[2]
        canonical = (row["body"] + row["hash"]).encode("utf-8")
        ch, sig = sr.seal_bytes(canonical, self.fx["chain_tip"], signer,
                                seed_hex)
        forged = canonical.replace(b"0.12", b"9.99")
        v = sr.verify_bytes(forged, ch, signer, sig, {signer: pk_hex})
        self.assertFalse(v["ok"])
        self.assertEqual(v["reasons"], ["bad_signature"])


class TestCrossLanguageVectors(unittest.TestCase):
    def test_vectors_replay_byte_exact(self):
        v = json.load(open(VECTORS))
        env = v["envelope"]
        r = Receipt(**env["receipt"])
        self.assertEqual(sr.canonical_bytes(r).hex(), env["canonical_hex"])
        self.assertEqual(sr.chain_head_hex(env["chain_tip"]), env["chain_head"])
        ch, sig = sr.seal_bytes(bytes.fromhex(env["canonical_hex"]),
                                env["chain_tip"], env["signer"],
                                v["ed25519"]["seed_hex"])
        self.assertEqual(ch, env["chain_head"])
        self.assertEqual(sig, env["signature_hex"])
        # round-trip through the interchange JSON form
        signed = sr.SignedReceipt(receipt=r, chain_head=ch,
                                  signer=env["signer"], signature=sig)
        self.assertEqual(sr.SignedReceipt.from_dict(signed.to_dict()), signed)
        self.assertEqual(
            len(json.loads(signed.to_canonical_json())["signature"]),
            128)


class TestVerifyOnlyNode(unittest.TestCase):
    def test_verifier_holds_no_secret(self):
        # A verify-only node builds its world from pubkeys alone.
        bk = _book_demo(1)
        signer, seed_hex, pk_hex = _fixed_id()
        signed = sr.seal(bk.entries[0], bk.replay(), signer, seed_hex)
        verifier_pubkeys = {signer: pk_hex}  # nothing else — no seed anywhere
        self.assertTrue(sr.verify_envelope(signed, verifier_pubkeys)["ok"])


if __name__ == "__main__":
    unittest.main()
